project04/config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users


  resources :line_items


  resources :carts


  get "store/index"

  resources :products

  # makes the '/' path go to /store/index and lets us easily access this with
  # store_path()
  root to: 'store#index', as: 'store' 

end

project04/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
</div>
<div id="columns">
    <div id="side">
        <ul>
            <li><a href="http://www...">Home</a></li>
            <li><a href="http://www.../faq">Questions</a></li>
            <li><a href="http://www.../news">News</a></li>
            <li><a href="http://www.../contact">Contacts</a></li>
        </ul>
        <div id="time">
            <%= Time.now %>
        </div>

        <% if session[:user_id] %>
            <ul>
                <li><%= link_to 'Products', products_path %></li>
                <li><%= link_to 'Users', users_path %></li>
            </ul>
            <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>
    </div>
    <div id="main">
        <%= yield %>
    </div>
</div>

</body>
</html>